export const constants = {
  REQUIRE_DAILY_WATER_CONSUMPTION_KEY: 'REQUIRE_DAILY_WATER_CONSUMPTION',
  REQUIRE_PROFILE_KEY: 'REQUIRE_PROFILE',
  REQUIRE_WORKOUT_PREFERENCE_KEY: 'REQUIRE_WORKOUT_PREFERENCE',
  REQUIRE_ACTIVE_DIET_KEY: 'REQUIRE_ACTIVE_DIET',
  REQUIRE_DIET_PREFERENCE_KEY: 'REQUIRE_DIET_PREFERENCE',
} as const
