export const constants = {
  REQUIRE_DAILY_WATER_CONSUMPTION_KEY: 'REQUIRE_DAILY_WATER_CONSUMPTION',
  REQUIRE_PROFILE_KEY: 'REQUIRE_PROFILE',
  REQUIRE_WORKOUT_CONFIG_KEY: 'REQUIRE_WORKOUT_CONFIG',
  REQUIRE_ACTIVE_DIET_KEY: 'REQUIRE_ACTIVE_DIET',
} as const
